package com.ssangyong.mapper;

import java.util.ArrayList;
import java.util.HashMap;

import com.ssangyong.common.remote.DataSet;
import com.ssangyong.dto.ApprovalLineData;
import com.ssangyong.dto.CodeData;
import com.ssangyong.dto.SYMCECOStatusData;
import com.ssangyong.dto.TCEcoModel;
import com.ssangyong.dto.VnetTeamInfoData;
import com.ssangyong.dto.VnetTeamReviewData;

public interface SYMCECOMapper {
	public void saveApprovalLine(ApprovalLineData paramMap);
	public ArrayList<ApprovalLineData> getApprovalLine(ApprovalLineData paramMap);
	public void removeApprovalLine(ApprovalLineData paramMap);
	public ArrayList<ApprovalLineData> loadApprovalLine(ApprovalLineData paramMap);
	public ArrayList<ApprovalLineData> loadSavedUserApprovalLine(ApprovalLineData paramMap);
	public void saveUserApprovalLine(ApprovalLineData map);
	public ArrayList<CodeData> getCode(String paramString);
	public String getNextECOSerial(String prefix);
	public ArrayList<SYMCECOStatusData> searchEOStatus(SYMCECOStatusData paramMap);
	public ArrayList<VnetTeamInfoData> getVnetTeamInfo(VnetTeamInfoData paramMap);
	public ArrayList<VnetTeamInfoData> getVnetTeamNames(VnetTeamInfoData paramMap);
	public HashMap<String, String> getECIfileInfo(DataSet ds);
	public void interfaceECI(DataSet ds);
	public void updateFileName(DataSet ds);
	public ArrayList<VnetTeamReviewData> getECIReviewInfo(DataSet ds);
	public void confirmECIReceived(DataSet ds);
	public void confirmECIReviewReceived(DataSet ds);
	public void refreshTCObject(DataSet ds);
	public void changeItemId(DataSet ds);
	public void refreshTCTimeStamp(DataSet ds);
	public void sendMail(DataSet ds);
    public void sendMailEai(DataSet ds);
    public void interfaceECONoToVnetEAI(DataSet ds);
	public void interfaceECONoToVnet(DataSet ds);
	public void updateECIRevisionWithInterface(DataSet ds);
	public ArrayList<HashMap<String, String>> searchECREAI(DataSet ds);
	public ArrayList<HashMap<String, String>> searchECR(DataSet ds);
	public ArrayList<HashMap<String, String>> searchECIEAI(DataSet ds);
	public ArrayList<HashMap<String, String>> searchECI(DataSet ds);
	public void changeECIStatus(DataSet ds);
	public void changeECOStatus(DataSet ds);
	public void changeMECOStatus(DataSet ds);
	public ArrayList<String> getProblemItems(DataSet ds);
	public ArrayList<String> getSolutionItems(DataSet ds);
	public ArrayList<String> checkEndtoEnd(DataSet ds);
	public String getAffectedProject(DataSet ds);
	public void makePartHistory(DataSet ds);
	public String getDuplicateCategoryInVC(DataSet ds);
	public ArrayList<HashMap<String, String>> checkECOEPL(DataSet ds);
	public void updateEcoStatus(DataSet ds);
	public void deleteApprovalLine(ApprovalLineData paramMap);
	public TCEcoModel getEcoInfoEAI(DataSet ds);
	public TCEcoModel getEcoInfo(DataSet ds);
	public ArrayList<HashMap<String, String>> getEcoWorkflowInfo(DataSet ds);
	public String childrenCount(String prefix);
	public String workflowCount(String prefix);
	public String getEcoRevisionPuid(String prefix);
	public ArrayList<HashMap<String,String>> searchUserOnVnet(DataSet ds);
	public String getInEcoFromECOBOMList(DataSet ds);
	public ArrayList<HashMap<String, String>> getColorIDWarningList(DataSet ds);
	public String getEcoEndItemCount(DataSet ds);
	public ArrayList<HashMap<String, String>> getColorIDChangingList(DataSet ds);
	public void makeBOMHistoryMaster(DataSet ds);
	public String isConnectedFunction(DataSet ds);
	public ArrayList<HashMap<String, String>> getCarProjectInEPL(DataSet ds);
	public ArrayList<HashMap<String, String>> getCANNOTGeneratedList(DataSet ds);
	public ArrayList<HashMap<String, String>> getCANNOTGeneratedReviseList(DataSet ds);
	public ArrayList<SYMCECOStatusData> searchECOCorrectionHistory(SYMCECOStatusData paramMap);
	public ArrayList<HashMap<String, String>> getRefEcoFromPartList(DataSet ds);
	public ArrayList<HashMap<String, Object>> getEcoDupApprovalLines(DataSet ds);
	public ArrayList<HashMap<String, String>> getOldRevNotMatchedParts(DataSet ds);
	public ArrayList<HashMap<String, String>> getIncorrectList(DataSet ds);
	public void updateStep(DataSet ds);
	public String getNMCDUpdatePartList(DataSet ds);
	public String getAdmin(DataSet ds);
	public ArrayList<HashMap<String,String>> getProjectCodeList(DataSet ds);
	public ArrayList<HashMap<String, String>> checkPowerTraing(DataSet ds);
}
